function value = LabelValue(ROI)

str = {'RightAccumbens',  'LeftAccumbens',...
    'RightAmygdala',   'LeftAmygdala',...
    'RightCaudate',    'LeftCaudate',...
    'RightHippocampus','LeftHippocampus',...
    'RightPallidum',   'LeftPallidum', ...
    'RightPutamen',    'LeftPutamen',...
    'RightThalamus',   'LeftThalamus'};
v = [23 30,...
    31 32,...
    36 37,...
    47 48,...
    55 56,...
    57 58,...
    59 60];
for i = 1:length(str)
    if  strcmp(ROI,str{i}) == 1
        value = v(i);
    end
end